# Generated by Django 5.0.3 on 2024-04-17 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0002_alter_game_player1_alter_game_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='current_player_games', to='connect4.player'),
        ),
    ]
