# Generated by Django 5.0.3 on 2024-04-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0003_alter_game_current_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='losses',
        ),
    ]
